blueprint:
  name: NFC Light Toggle with Color, Transition & Log
  description: Toggle a light via NFC tag with brightness, color, transition and logbook entry
  domain: automation

  input:
    nfc_tag_id:
      name: NFC Tag ID
      description: The NFC tag ID (e.g. d5a62d83-98a2-4af4-b63d-8385f81aa628)
      selector:
        text: {}

    light_entity:
      name: Light
      selector:
        entity:
          domain: light

    brightness:
      name: Brightness (%)
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    transition:
      name: Transition (seconds)
      default: 2
      selector:
        number:
          min: 0
          max: 10
          unit_of_measurement: "s"

    rgb_color:
      name: RGB Color (optional)
      default: []
      selector:
        color_rgb: {}

    color_temp:
      name: Color temperature (Kelvin, optional)
      default: 0
      selector:
        number:
          min: 2000
          max: 6500
          unit_of_measurement: "K"

trigger:
  - platform: tag
    tag_id: !input nfc_tag_id

variables:
  user_name: >
    {{ (states.person
        | selectattr('attributes.user_id','defined')
        | selectattr('attributes.user_id','eq', trigger.context.user_id)
        | map(attribute='name')
        | list
        | first) | default('Unknown') }}

action:
  - choose:
      # LIGHT IS ON → TURN OFF
      - conditions:
          - condition: state
            entity_id: !input light_entity
            state: "on"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light_entity
            data:
              transition: !input transition

          - service: logbook.log
            data:
              name: NFC Light
              message: "{{ user_name }} turned {{ !input light_entity }} OFF (NFC)"
              entity_id: !input light_entity

    # LIGHT IS OFF → TURN ON
    default:
      - service: light.turn_on
        target:
          entity_id: !input light_entity
        data:
          brightness_pct: !input brightness
          transition: !input transition
          rgb_color: >
            {% if !input rgb_color != [] %}
              {{ !input rgb_color }}
            {% endif %}
          kelvin: >
            {% if !input color_temp | int > 0 %}
              {{ !input color_temp }}
            {% endif %}

      - service: logbook.log
        data:
          name: NFC Light
          message: "{{ user_name }} turned {{ !input light_entity }} ON (NFC)"
          entity_id: !input light_entity

mode: single
