blueprint:
  name: NFC Light Toggle mit Farbe, Transition & Log
  description: Schaltet ein Licht per NFC ein/aus mit Helligkeit, Farbe, Transition und Logbucheintrag
  domain: automation

  input:
    nfc_tag:
      name: NFC Tag
      selector:
        tag: {}

    light_entity:
      name: Lampe
      selector:
        entity:
          domain: light

    brightness:
      name: Helligkeit (%)
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    transition:
      name: Transition (Sekunden)
      default: 2
      selector:
        number:
          min: 0
          max: 10
          unit_of_measurement: "s"

    rgb_color:
      name: RGB Farbe (optional)
      default: []
      selector:
        color_rgb: {}

    color_temp:
      name: Farbtemperatur (Kelvin, optional)
      default: 0
      selector:
        number:
          min: 2000
          max: 6500
          unit_of_measurement: "K"

trigger:
  - platform: tag
    tag_id: !input nfc_tag

variables:
  user: "{{ trigger.context.user_id }}"
  user_name: >
    {{ (states.person
        | selectattr('attributes.user_id','defined')
        | selectattr('attributes.user_id','eq', trigger.context.user_id)
        | map(attribute='name')
        | list
        | first) | default('Unbekannt') }}

action:
  - choose:
      # LICHT IST AN → AUS
      - conditions:
          - condition: state
            entity_id: !input light_entity
            state: "on"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light_entity
            data:
              transition: !input transition

          - service: logbook.log
            data:
              name: NFC Licht
              message: "{{ user_name }} hat {{ !input light_entity }} AUS geschaltet (NFC)"
              entity_id: !input light_entity

    # LICHT IST AUS → EIN
    default:
      - service: light.turn_on
        target:
          entity_id: !input light_entity
        data:
          brightness_pct: !input brightness
          transition: !input transition
          rgb_color: >
            {% if !input rgb_color != [] %}
              {{ !input rgb_color }}
            {% endif %}
          kelvin: >
            {% if !input color_temp | int > 0 %}
              {{ !input color_temp }}
            {% endif %}

      - service: logbook.log
        data:
          name: NFC Licht
          message: "{{ user_name }} hat {{ !input light_entity }} EIN geschaltet (NFC)"
          entity_id: !input light_entity

mode: single
